### ISSUE TITLE
[Task] 유저 정보에 대한 서버 기능 구현하기

### ISSUE THREAD

**Issue by jacobways** [jacobways/EasyInvesting#5]
### To Do List (아래 직접 입력하기)
- [x] User DB 테이블 제작
- [x] 회원가입 API 제작
- [x] 회원정보 수정 API 제작

### Labels (오른쪽에서 테마별로 각 1개, 총 2개 선택)
- Part : client, server, deploy
- 단계 : Bare Minimum, Advanced, Nightmare
- 시간 : `3h` ~ `24h`

### Projects 선택
- 1차 기능구현

### Milestone 선택
- 1차 기능구현
